version: "3.8"

services:
  # container name, chosen by me
  pharmacy:
    build: ./
    ports:
      - "8080:8080"
    environment:
      DB_IP: db
      db_username: postgres
      db_password: EDGG3gD-2b*f5D434G4fCbDDG-23fB*2
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: EDGG3gD-2b*f5D434G4fCbDDG-23fB*2
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:





